version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build
  post_build:
    commands:
      - echo Build completed
      - echo Copying build files to S3...
      - if [ -d ".next" ]; then aws s3 cp .next/ s3://codebuildbucket112/.next --recursive; else echo "Build directory not found"; exit 1; fi

artifacts:
  files:
    - '**/*'
  base-directory: '.next'


