version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build
  post_build:
    commands:
      - echo Build completed
      # Add S3 copy commands
      - aws s3 cp build/ s3://codebuildbucket112 --recursive
     

artifacts:
  files:
    - '**/*'
  base-directory: 'build'